apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  volumes:
    - name: host-vol
      hostPath:
        path: /var/log
        type: Directory
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-vol
          mountPath: /logs
