apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spsphostpath
spec:
  crd:
    spec:
      names:
        kind: K8sPSPHostPath
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spsphostpath

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          volume := input.review.object.spec.volumes[_]
          volume.hostPath.path != ""
          msg := sprintf("hostPath volume %v is not allowed", [volume.name])
        }
