apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers-cluster-binding
  namespace: sales
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
  - kind: Group
    name: grp-developers
    apiGroup: rbac.authorization.k8s.io